sonar.projectKey=dotnet-project
sonar.working.directory=C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\JALAGAM\\DotnetCoverageDemo
sonar.pullrequest.cache.basepath=C:\\Users\\JALAGAM\\DotnetCoverageDemo

317CDB6F-888F-447E-B1F4-36F5809EE447.sonar.projectKey=dotnet-project:317CDB6F-888F-447E-B1F4-36F5809EE447
317CDB6F-888F-447E-B1F4-36F5809EE447.sonar.projectName=DemoApi
317CDB6F-888F-447E-B1F4-36F5809EE447.sonar.projectBaseDir=C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi
317CDB6F-888F-447E-B1F4-36F5809EE447.sonar.sourceEncoding=utf-8
317CDB6F-888F-447E-B1F4-36F5809EE447.sonar.tests=
317CDB6F-888F-447E-B1F4-36F5809EE447.sonar.sources=\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\Calculator.cs",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\Program.cs",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\obj\\Debug\\net8.0\\DemoApi.GlobalUsings.g.cs",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\obj\\Debug\\net8.0\\DemoApi.AssemblyInfo.cs",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\obj\\Debug\\net8.0\\DemoApi.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\appsettings.Development.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\appsettings.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\DemoApi.http",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\Properties\\launchSettings.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\obj\\DemoApi.csproj.nuget.dgspec.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\obj\\project.assets.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\bin\\Debug\\net8.0\\DemoApi.deps.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\bin\\Debug\\net8.0\\DemoApi.runtimeconfig.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi\\obj\\Debug\\net8.0\\staticwebassets.build.json"

317CDB6F-888F-447E-B1F4-36F5809EE447.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\0",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\2"
317CDB6F-888F-447E-B1F4-36F5809EE447.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\0\\Issues.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\2\\Issues.json"
317CDB6F-888F-447E-B1F4-36F5809EE447.sonar.cs.scanner.telemetry=\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\0\\Telemetry.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\2\\Telemetry.json"

317CDB6F-888F-447E-B1F4-36F5809EE447.sonar.working.directory=C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\.sonar\\mod0
133CE88D-0A6F-4738-AC7F-FAB613826335.sonar.projectKey=dotnet-project:133CE88D-0A6F-4738-AC7F-FAB613826335
133CE88D-0A6F-4738-AC7F-FAB613826335.sonar.projectName=DemoApi.Tests
133CE88D-0A6F-4738-AC7F-FAB613826335.sonar.projectBaseDir=C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi.Tests
133CE88D-0A6F-4738-AC7F-FAB613826335.sonar.sourceEncoding=utf-8
133CE88D-0A6F-4738-AC7F-FAB613826335.sonar.sources=
133CE88D-0A6F-4738-AC7F-FAB613826335.sonar.tests=\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi.Tests\\obj\\DemoApi.Tests.csproj.nuget.dgspec.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi.Tests\\obj\\project.assets.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi.Tests\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi.Tests\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi.Tests\\bin\\Debug\\net8.0\\DemoApi.deps.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi.Tests\\bin\\Debug\\net8.0\\DemoApi.runtimeconfig.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi.Tests\\bin\\Debug\\net8.0\\DemoApi.Tests.deps.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi.Tests\\bin\\Debug\\net8.0\\DemoApi.Tests.runtimeconfig.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\DemoApi.Tests\\UnitTest1.cs"

133CE88D-0A6F-4738-AC7F-FAB613826335.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\1",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\3"
133CE88D-0A6F-4738-AC7F-FAB613826335.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\1\\Issues.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\3\\Issues.json"
133CE88D-0A6F-4738-AC7F-FAB613826335.sonar.cs.scanner.telemetry=\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\1\\Telemetry.json",\
"C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\3\\Telemetry.json"

133CE88D-0A6F-4738-AC7F-FAB613826335.sonar.working.directory=C:\\Users\\JALAGAM\\DotnetCoverageDemo\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.cs.vscoveragexml.reportsPaths=coverage.xml
sonar.exclusions=coverage.xml
sonar.visualstudio.enable=false

sonar.modules=317CDB6F-888F-447E-B1F4-36F5809EE447,133CE88D-0A6F-4738-AC7F-FAB613826335

